language: python
cache: pip

matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
    - python: "pypy"

script:
  - python setup.py test
